alias ignore='git update-index --assume-unchanged'
alias unignore='git update-index --no-assume-unchanged'
#alias allchange='gitk --all $(git log -g --pretty=format:%h)'
alias checkout_all='git submodule foreach git checkout master'
alias mergeall='git submodule foreach git merge origin/master'
alias updateall='git merge origin/master; git submodule update; git submodule foreach git checkout master; git submodule foreach git merge origin/master; git submodule update; ~/bin/taggen; rm -rf ~/.cache/ctrlp/*'
alias fetchall='git fetch; git merge origin/master; git submodule update; git submodule foreach git checkout master; git submodule foreach git merge origin/master; git submodule update'
alias deploy='echo "qlNP5SUoy4EOHet" ; cap deploy'
alias review='gitk HEAD@{1}..HEAD@{0} &'
alias compare='git diff master.. | kompare - &'
